{{- include "sch.config.init" (list . "ibm-connect-direct.sch.chart.config.values") }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $appName := include "sch.names.appName" (list .) }}
{{- if .Values.route.enabled }}
{{- if (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{  $appName  }}
    app.kubernetes.io/instance: {{  .Release.Name  }}
    app.kubernetes.io/managed-by: {{  .Release.Service  }}
    helm.sh/chart: {{  include "ibm-connect-direct.chart" .  }}
    release: {{  .Release.Name  }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 50
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}
{{- end }}
