apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: ibm-connect-direct
    helm.sh/chart: <helm chart version>
    release: <helm instance name>
  name: <pvc name>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: <PV name for bound>
