apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <PVC_name>
spec:
  storageClassName: "standard"
  selector:
    matchExpressions:
      - {key: intent, operator: In, values: [<PV_name>]}
  accessModes: [ "ReadOnlyMany" ]
  resources:
    requests:
      storage: "500Mi"